export class InteractionHandler {
  initialized: boolean;
  cachedElements: Map<any, any>;
  activeRipples: Set<any>;
  clickHandlers: Map<any, any>;
  scrollHandlers: any[];
  init(): Promise<void>;
  initRippleEffects(): void;
  createRipple(button: any, event: any): void;
  removeRipple(ripple: any): void;
  initCardHoverEffects(): void;
  applyCardHoverEffect(card: any, isHovering: any): void;
  initButtonInteractions(): void;
  handleButtonClick(button: any, event: any): void;
  setButtonLoading(button: any, isLoading: any): void;
  initFormInteractions(): void;
  handleFormSubmit(form: any, event: any): void;
  enableForm(form: any): void;
  handleInputValidation(input: any): void;
  showInputValidation(input: any, isValid: any, errorMessage: any): void;
  enhanceInputFocus(input: any, isFocused: any): void;
  initKeyboardNavigation(): void;
  handleKeyboardNavigation(event: any): void;
  initSkipLinks(): void;
  scrollToTop(): void;
  toggleMobileMenu(): void;
  focusSearchInput(): void;
  handleEscapeKey(event: any): void;
  closeModal(modal: any): void;
  setupEventDelegation(): void;
  handleDelegatedClick(event: any): void;
  handleExternalLinkClick(link: any, event: any): void;
  handleDownloadLinkClick(link: any, event: any): void;
  handleSocialLinkClick(link: any, event: any): void;
  addClickHandler(type: any, handler: any): void;
  removeClickHandler(type: any): void;
  emitInteractionEvent(type: any, data: any): void;
  destroy(): void;
}
export default InteractionHandler;
//# sourceMappingURL=interaction-handler.d.ts.map
